name: IBC Testing with Emerynet and Devnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ibc-testing:
    runs-on: ubuntu-latest

    env:
      EMERYNET_BALANCE_FILE: emerynet_file.txt
      DEVNET_BALANCE_FILE: devnet_file.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose services
        run: docker-compose -f docker-compose-testnet.yaml up -d

      - name: Query and store balance for Emerynet Wallet
        run: |
          agd query bank balances agoric10emrzln03exuc9uv98mjwmp95735mjm6k2n9xm \
            --chain-id=agoric-emerynet-8 \
            --node="https://emerynet.rpc.agoric.net:443" \
            -o json | jq -r '.balances[] | select(.denom == "ubld") | .amount | tonumber' > $EMERYNET_BALANCE_FILE

      - name: Query and store balance for Devnet Wallet
        run: |
          agd query bank balances agoric1khw65emzav9t0cdhj3aw9x2v7m60jekjdf4whl \
           --chain-id=agoricdev-23 \
            --node="https://devnet.rpc.agoric.net" \
            -o json | jq -r '.balances[] | select(.denom == "ubld") | .amount | tonumber' > $DEVNET_BALANCE_FILE

      - name: Waiting for Channel to be Initialized
        run: |
          timeout 600 bash -c "\
          until line=\$(docker logs relayer 2>&1 | grep 'OpenInitChannel'); do
            echo 'Waiting for channel to start...'
            sleep 1
          done
          if [[ -n \$line ]]; then
            channel_id=\$(echo \$line | awk -F'channel_id: ' '{print \$2}' | awk -F', ' '{print \$1}')
            echo \"Channel ID extracted: \$channel_id\"
            echo \$channel_id > channel_id.txt
          else
            echo 'No channel found before timeout.'
            exit 1
          fi"

      - name: Waiting for Channel Confirmation
        run: |
          channel_id=$(cat channel_id.txt)
          timeout 300 bash -c "\
          until docker logs relayer 2>&1 | grep -q 'OpenConfirmChannel.*$channel_id'; do
            echo 'Waiting for OpenConfirmChannel with $channel_id...'
            sleep 1
          done
          echo 'Confirmation log found for $channel_id'"

      - name: Transfer tokens via IBC
        run: |
          docker exec relayer hermes --config /workspace/relayer/config-testnet.toml tx ft-transfer --src-chain agoric-emerynet-8 --src-channel $(cat channel_id.txt) \
          --dst-chain agoricdev-23 --src-port transfer --amount 100 --denom 'ubld' --timeout-seconds 1000 && \
          sleep 5
