name: IBC Testing with Emerynet and Devnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ibc-testing:
    name: Inter-Blockchain Communication Testing
    runs-on: ubuntu-latest

    env:
      EMERYNET_BALANCE_FILE: emerynet_file.txt
      DEVNET_BALANCE_FILE: devnet_file.txt
      EMERYNET_CHAIN_ID: agoric-emerynet-8
      DEVNET_CHAIN_ID: agoricdev-23
      EMERYNET_NODE: https://emerynet.rpc.agoric.net:443
      DEVNET_NODE: https://devnet.rpc.agoric.net
      WALLET_ADDRESS_EMERYNET: agoric10emrzln03exuc9uv98mjwmp95735mjm6k2n9xm
      WALLET_ADDRESS_DEVNET: agoric1khw65emzav9t0cdhj3aw9x2v7m60jekjdf4whl
      RELAYER_CONFIG: /workspace/relayer/config-testnet.toml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Testnet Docker Services
        run: docker-compose -f docker-compose-testnet.yaml up -d

      - name: Fetch Emerynet Wallet Balance
        run: |
          agd query bank balances $WALLET_ADDRESS_EMERYNET \
            --chain-id=$EMERYNET_CHAIN_ID \
            --node="$EMERYNET_NODE" \
            -o json | jq -r '.balances[] | select(.denom == "ubld") | .amount | tonumber' > $EMERYNET_BALANCE_FILE

      - name: Fetch Devnet Wallet Balance
        run: |
          agd query bank balances $WALLET_ADDRESS_DEVNET \
            --chain-id=$DEVNET_CHAIN_ID \
            --node="$DEVNET_NODE" \
            -o json | jq -r '.balances[] | select(.denom == "ubld") | .amount | tonumber' > $DEVNET_BALANCE_FILE

      - name: Monitor Channel Initialization
        run: |
          timeout 600 bash -c "\
          until line=\$(docker logs relayer 2>&1 | grep 'OpenInitChannel'); do
            echo 'Waiting for channel initialization...'
            sleep 1
          done
          if [[ -n \$line ]]; then
            channel_id=\$(echo \$line | awk -F'channel_id: ' '{print \$2}' | awk -F', ' '{print \$1}')
            echo \"Channel ID extracted: \$channel_id\"
            echo \$channel_id > channel_id.txt
          else
            echo 'Channel initialization timed out.'
            exit 1
          fi"

      - name: Confirm Channel Status
        run: |
          channel_id=$(cat channel_id.txt)
          timeout 300 bash -c "\
          until docker logs relayer 2>&1 | grep -q 'OpenConfirmChannel.*$channel_id'; do
            echo 'Awaiting confirmation for channel ID: $channel_id...'
            sleep 1
          done
          echo 'Channel ID $channel_id confirmed.'"

      - name: Execute IBC Token Transfer
        run: |
          docker exec relayer hermes --config $RELAYER_CONFIG tx ft-transfer --src-chain $EMERYNET_CHAIN_ID --src-channel $(cat channel_id.txt) \
          --dst-chain $DEVNET_CHAIN_ID --src-port transfer --amount 100 --denom 'ubld' --timeout-seconds 1000 && \
          sleep 5

      - name: Verify Token Transfer on Emerynet
        run: |
          NEW_EMERYNET_BALANCE=$(agd query bank balances $WALLET_ADDRESS_EMERYNET \
          --chain-id=$EMERYNET_CHAIN_ID \
          --node="$EMERYNET_NODE" \
          -o json | jq -r '.balances[] | select(.denom == "ubld") | .amount | tonumber')
          ORIGINAL_EMERYNET_BALANCE=$(cat $EMERYNET_BALANCE_FILE)
          BALANCE_DIFFERENCE=$((NEW_EMERYNET_BALANCE - ORIGINAL_EMERYNET_BALANCE))
          if [ "$BALANCE_DIFFERENCE" -ne 100 ]; then
            echo "Token transfer discrepancy detected: Expected 100, found $BALANCE_DIFFERENCE."
            exit 1
          else
            echo "Token transfer validated: Balance difference is exactly 100."
          fi
